version: 2
updates:
  # NuGet package updates
  - package-ecosystem: nuget
    directory: /
    schedule:
      interval: "weekly"
      day: "sunday"
    open-pull-requests-limit: 3
    rebase-strategy: disabled
    groups:
      testcontainers:
        patterns: ['Testcontainers*', 'Microcks*']
      microsoft:
        patterns: [Microsoft.*, System.*]
        exclude-patterns:
         - Microsoft.Sbom.Targets
         - Microsoft.NET.Test.Sdk
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
    open-pull-requests-limit: 3
    rebase-strategy: disabled
